add collection support (zipfile)
git-svn-id: https://vcs.maemo.org/svn/numptyphysics/trunk@111 2afca267-d0a4-46bd-89a9-2591803afc3f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4999,15 +4999,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_HILDON_CFLAGS="$HILDON_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"hildon-1 hildon-fm-2 libosso libossoemailinterface
-   			     glib-2.0 dbus-1\"") >&5
-  ($PKG_CONFIG --exists --print-errors "hildon-1 hildon-fm-2 libosso libossoemailinterface
-   			     glib-2.0 dbus-1") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"hildon-1 hildon-fm-2 libossoemailinterface\"") >&5
+  ($PKG_CONFIG --exists --print-errors "hildon-1 hildon-fm-2 libossoemailinterface") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_HILDON_CFLAGS=`$PKG_CONFIG --cflags "hildon-1 hildon-fm-2 libosso libossoemailinterface
-   			     glib-2.0 dbus-1" 2>/dev/null`
+  pkg_cv_HILDON_CFLAGS=`$PKG_CONFIG --cflags "hildon-1 hildon-fm-2 libossoemailinterface" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -5020,15 +5017,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_HILDON_LIBS="$HILDON_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"hildon-1 hildon-fm-2 libosso libossoemailinterface
-   			     glib-2.0 dbus-1\"") >&5
-  ($PKG_CONFIG --exists --print-errors "hildon-1 hildon-fm-2 libosso libossoemailinterface
-   			     glib-2.0 dbus-1") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"hildon-1 hildon-fm-2 libossoemailinterface\"") >&5
+  ($PKG_CONFIG --exists --print-errors "hildon-1 hildon-fm-2 libossoemailinterface") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_HILDON_LIBS=`$PKG_CONFIG --libs "hildon-1 hildon-fm-2 libosso libossoemailinterface
-   			     glib-2.0 dbus-1" 2>/dev/null`
+  pkg_cv_HILDON_LIBS=`$PKG_CONFIG --libs "hildon-1 hildon-fm-2 libossoemailinterface" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -5047,11 +5041,9 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        HILDON_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "hildon-1 hildon-fm-2 libosso libossoemailinterface
-   			     glib-2.0 dbus-1"`
+	        HILDON_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "hildon-1 hildon-fm-2 libossoemailinterface"`
         else
-	        HILDON_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "hildon-1 hildon-fm-2 libosso libossoemailinterface
-   			     glib-2.0 dbus-1"`
+	        HILDON_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "hildon-1 hildon-fm-2 libossoemailinterface"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$HILDON_PKG_ERRORS" >&5
@@ -5232,6 +5224,71 @@ if test $ac_cv_lib_X11_main = yes; then
 _ACEOF
 
   LIBS="-lX11 $LIBS"
+
+fi
+
+
+{ echo "$as_me:$LINENO: checking for main in -lz" >&5
+echo $ECHO_N "checking for main in -lz... $ECHO_C" >&6; }
+if test "${ac_cv_lib_z_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lz  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_z_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_z_main=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_z_main" >&5
+echo "${ECHO_T}$ac_cv_lib_z_main" >&6; }
+if test $ac_cv_lib_z_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBZ 1
+_ACEOF
+
+  LIBS="-lz $LIBS"
 
 fi
 
